name: Ruff

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Ruff lint
        run: uv run --locked --only-group dev ruff check .

      - name: Ruff format
        run: uv run --locked --only-group dev ruff format --check .
