name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install spanish_nlp
        run: pip install .

      - name: Run tests
        run: pytest tests/
        continue-on-error: false

      - name: Build package
        run: |
          hatchling build
          export VERSION=$(hatchling version | awk '{print $NF}')
          echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Add tag to repository
        if: success()
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: v${{ env.PACKAGE_VERSION }}

